version: '3.3'

services:
  web:
    build:
      context: .
    domainname: magento2.docker
    hostname: magento2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
