version: '3.2'

services:
  web:
    build:
      context: .
    domainname: magento2.docker
    hostname: magento2
    ports:
      - "80:80"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - COMPOSER_HOME=/root/composer
